# Generated by Django 4.2.5 on 2023-10-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='title',
        ),
    ]
